# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = mega
BOARD_SUB    = atmega1280
ARDUINO_DIR  = /usr/local/share/arduino

include /usr/local/share/arduino-makefile/Arduino.mk
